---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:3.0.9
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /etc/dockerconfigs/sonarr:/config
      - /mnt/volume1/series:/tv
      - /mnt/volume1/downloadclient-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:4.1.0
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /etc/dockerconfigs/radarr:/config
      - /mnt/volume1/movies:/movies #optional
      - /mnt/volume1/downloadclient-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:1.28.2
    container_name: plex
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /etc/dockerconfigs/plex:/config
      - /mnt/volume1/movies:/movies
      - /mnt/volume1/series:/series
      - /dev/dri:/dev/dri
    restart: unless-stopped
    ports:
      - 32400:32400
  nzbget:
    image: lscr.io/linuxserver/nzbget:21.1.20220908
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - NZBGET_USER=nzbget
      - NZBGET_PASS=tegbzn6789
    volumes:
      - /etc/dockerconfigs/nzbget:/config
      - /mnt/volume1/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
  # unifi-controller:
  #   image: lscr.io/linuxserver/unifi-controller:latest
  #   container_name: unifi-controller
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - MEM_LIMIT=1024 #optional
  #     - MEM_STARTUP=1024 #optional
  #   volumes:
  #     - /etc/dockerconfigs/unifi:/config
  #   ports:
  #     - 8443:8443
  #     - 3478:3478/udp
  #     - 10001:10001/udp
  #     - 8080:8080
  #     - 1900:1900/udp #optional
  #     - 6789:6789 #optional
  #     - 5514:5514/udp #optional
  #   restart: unless-stopped