---
# tasks file for powertop

- name: Install powertop.
  ansible.builtin.package:
    name: "{{ powertop_packages }}"
    state: present

- name: Configure powertop service.
  template:
    src: powertop.service.j2
    dest: /etc/systemd/system/powertop.service
  tags: powertop
  notify: daemon reload

- name: Enable powertop.
  ansible.builtin.service:
    name: "{{ powertop_service }}"
    state: started
    enabled: yes