---

- name: Install Docker dependencies.
  ansible.builtin.package:
    name: "{{ docker_deps_packages }}"
    state: present

- name: Add Docker GPG apt Key
  apt_key:
    url: "{{ docker_gpg_url }}"
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: Install Docker.
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: present

- name: Install Python Docker module
  pip:
    name: docker

- name: Add adminstrator to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install Docker Compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    mode: u+x,g+x,o+x
